export const data = [{
	id: 1,
	name: 'Max Mustermann',
	email: 'max.mustermann@mail.com',
	rating: 3.5,
	age: 30,
	gender: 'male',
	phone: '+1 (123) 456-7890',
	address: 'Vienna, Austria',
	progress: 100,
	verified: false,
	registrationDate: new Date(2019, 1, 1),
	status: 'Active',
	role: 'Admin',
	country: 'Austria',
	countryCode: 'at',
	city: 'Vienna',
	language: 'German',
	tokens: 100,
}
	, {
	id: 2,
	name: 'John Doe',
	email: 'juan.perez@mail.com',
	rating: 4.5,
	age: 25,
	gender: 'female',
	phone: '+1 (456) 456-7890',
	address: 'Washington DC, USA',
	progress: 100,
	verified: true,
	registrationDate: new Date(2022, 1, 1),
	status: 'Active',
	role: 'Admin',
	country: 'USA',
	countryCode: 'us',
	city: 'Washington DC',
	language: 'English',
	tokens: 72,
}, {
	id: 3,
	name: 'Juan Pérez',
	email: 'juan.perez@mail.com',
	rating: 2,
	age: 22,
	gender: 'male',
	phone: '+1 (789) 456-7890',
	address: 'Madrid, Spain',
	progress: 50,
	verified: true,
	registrationDate: new Date(2021, 1, 1),
	status: 'Inactive',
	role: 'User',
	country: 'Spain',
	countryCode: 'es',
	city: 'Madrid',
	language: 'Spanish',
	tokens: 12
}, {
	id: 4,
	name: 'Mario Rossi',
	email: 'mario.rossi@mail.com',
	rating: 0,
	age: 22,
	gender: 'male',
	phone: '+1 (101) 456-7890',
	address: '123 Main St, Anytown, USA',
	progress: 25,
	verified: true,
	registrationDate: new Date(2021, 1, 1),
	status: 'Inactive',
	role: 'User',
	country: 'Italy',
	countryCode: 'it',
	city: 'Rome',
	language: 'Italian',
	tokens: 10,
}, {
	id: 5,
	name: 'Andrei Vinca',
	email: 'andrei.vinca@outlook.com',
	rating: 1.5,
	age: 37,
	gender: 'male',
	phone: '+1 (112) 456-7890',
	progress: 10,
	address: 'Cluj-Napoca, Romania',
	verified: true,
	registrationDate: new Date(2021, 1, 1),
	status: 'Inactive',
	role: 'User',
	country: 'Romania',
	countryCode: 'ro',
	city: 'Bucharest',
	language: 'Romanian',
	tokens: 99
}, {
	id: 6,
	name: 'Jean Dupont',
	email: 'jean.dupont@mail.com',
	rating: 0,
	age: 22,
	gender: 'male',
	phone: '+1 (131) 456-7890',
	address: 'Paris, France',
	progress: 12,
	verified: true,
	registrationDate: new Date(2021, 1, 1),
	status: 'Inactive',
	role: 'User',
	country: 'France',
	countryCode: 'fr',
	city: 'Paris',
	language: 'French',
	tokens: 45
}]