'use client';

import { CountryIcon } from '@/lib/icons/country-icon';
import { stringAvatar } from '@/util/avatar-util';
import { Stack, Avatar, Chip, LinearProgress, Rating, MenuItem, ListItemIcon, FormControlLabel, Checkbox, Typography, useMediaQuery, Theme, Button } from '@mui/material';
import { AbsoluteHeightContainer, Action, ColumnsFillRowSpacePlugin, ColumnSortPlugin, CustomBodyCellContentRenderPlugin, EmptyDataPlugin, ColumnDef, HighlightColumnPlugin, MosaicDataTable, Order, PaddingPluggin, PinnedColumnsPlugin, RowActionsPlugin, RowExpansionPlugin, RowSelectionPlugin, SkeletonLoadingPlugin, useGridPlugins, usePluginWithParams, useResponsiveHeadCellVisible, useRowExpansionStore, SummaryRowPlugin, FilterRowPlugin, DefaultStringFilterOptions, Filter, DefaultNumberDateFilterOptions, RowDetailPlugin, createRowDetailStore, createResponsivePin, createRowSelectionStore, createFilterRowStore } from 'mosaic-data-table';
import { useCallback, useMemo, useState } from 'react';
import DeleteIcon from "@mui/icons-material/Delete";
import EditIcon from "@mui/icons-material/Edit";
import { useSelection } from './hooks/use-selection';
import dayjs from 'dayjs';
import { create } from 'domain';

const data = [{
    id: 1,
    name: 'Max Mustermann',
    email: 'max.mustermann@mail.com',
    rating: 3.5,
    age: 30,
    gender: 'male',
    phone: '+1 (123) 456-7890',
    address: 'Vienna, Austria',
    progress: 100,
    verified: false,
    registrationDate: new Date(2019, 1, 1),
    status: 'Active',
    role: 'Admin',
    country: 'Austria',
    countryCode: 'at',
    city: 'Vienna',
    language: 'German',
    tokens: 100,
}
, {
    id: 2,
    name: 'John Doe',
    email: 'juan.perez@mail.com',
    rating: 4.5,
    age: 25,
    gender: 'female',
    phone: '+1 (456) 456-7890',
    address: 'Washington DC, USA',
    progress: 100,
    verified: true,
    registrationDate: new Date(2022, 1, 1),
    status: 'Active',
    role: 'Admin',
    country: 'USA',
    countryCode: 'us',
    city: 'Washington DC',
    language: 'English',
    tokens: 72,
}, {
    id: 3,
    name: 'Juan Pérez',
    email: 'juan.perez@mail.com',
    rating: 2,
    age: 22,
    gender: 'male',
    phone: '+1 (789) 456-7890',
    address: 'Madrid, Spain',
    progress: 50,
    verified: true,
    registrationDate: new Date(2021, 1, 1),
    status: 'Inactive',
    role: 'User',
    country: 'Spain',
    countryCode: 'es',
    city: 'Madrid',
    language: 'Spanish',
    tokens: 12
}, {
    id: 4,
    name: 'Mario Rossi',
    email: 'mario.rossi@mail.com',
    rating: 0,
    age: 22,
    gender: 'male',
    phone: '+1 (101) 456-7890',
    address: '123 Main St, Anytown, USA',
    progress: 25,
    verified: true,
    registrationDate: new Date(2021, 1, 1),
    status: 'Inactive',
    role: 'User',
    country: 'Italy',
    countryCode: 'it',
    city: 'Rome',
    language: 'Italian',
    tokens: 10,
}, {
    id: 5,
    name: 'Andrei Vinca',
    email: 'andrei.vinca@outlook.com',
    rating: 1.5,
    age: 37,
    gender: 'male',
    phone: '+1 (112) 456-7890',
    progress: 10,
    address: 'Cluj-Napoca, Romania',
    verified: true,
    registrationDate: new Date(2021, 1, 1),
    status: 'Inactive',
    role: 'User',
    country: 'Romania',
    countryCode: 'ro',
    city: 'Bucharest',
    language: 'Romanian',
    tokens: 99
}, {
    id: 6,
    name: 'Jean Dupont',
    email: 'jean.dupont@mail.com',
    rating: 0,
    age: 22,
    gender: 'male',
    phone: '+1 (131) 456-7890',
    address: 'Paris, France',
    progress: 12,
    verified: true,
    registrationDate: new Date(2021, 1, 1),
    status: 'Inactive',
    role: 'User',
    country: 'France',
    countryCode: 'fr',
    city: 'Paris',
    language: 'French',
    tokens: 45
}, 


















// {
//     "id": 7,
//     "name": "Anna Schmidt",
//     "email": "anna.schmidt@mail.com",
//     "rating": 4.0,
//     "age": 28,
//     "gender": "female",
//     "phone": "+1 (141) 456-7890",
//     "address": "Berlin, Germany",
//     "progress": 80,
//     "verified": true,
//     "registrationDate": "2020-02-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Berlin",
//     "language": "German",
//     "tokens": 60
// },
// {
//     "id": 8,
//     "name": "Luca Bianchi",
//     "email": "luca.bianchi@mail.com",
//     "rating": 3.0,
//     "age": 35,
//     "gender": "male",
//     "phone": "+1 (151) 456-7890",
//     "address": "Milan, Italy",
//     "progress": 70,
//     "verified": true,
//     "registrationDate": "2020-02-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Milan",
//     "language": "Italian",
//     "tokens": 55
// },
// {
//     "id": 9,
//     "name": "Sophie Martin",
//     "email": "sophie.martin@mail.com",
//     "rating": 4.2,
//     "age": 29,
//     "gender": "female",
//     "phone": "+1 (161) 456-7890",
//     "address": "Lyon, France",
//     "progress": 90,
//     "verified": true,
//     "registrationDate": "2019-02-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Lyon",
//     "language": "French",
//     "tokens": 85
// },
// {
//     "id": 10,
//     "name": "Carlos Gomez",
//     "email": "carlos.gomez@mail.com",
//     "rating": 3.8,
//     "age": 40,
//     "gender": "male",
//     "phone": "+1 (171) 456-7890",
//     "address": "Barcelona, Spain",
//     "progress": 60,
//     "verified": true,
//     "registrationDate": "2018-02-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Barcelona",
//     "language": "Spanish",
//     "tokens": 40
// },
// {
//     "id": 11,
//     "name": "Laura Müller",
//     "email": "laura.muller@mail.com",
//     "rating": 4.1,
//     "age": 27,
//     "gender": "female",
//     "phone": "+1 (181) 456-7890",
//     "address": "Hamburg, Germany",
//     "progress": 85,
//     "verified": true,
//     "registrationDate": "2020-03-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Hamburg",
//     "language": "German",
//     "tokens": 70
// },
// {
//     "id": 12,
//     "name": "Giuseppe Verdi",
//     "email": "giuseppe.verdi@mail.com",
//     "rating": 3.9,
//     "age": 45,
//     "gender": "male",
//     "phone": "+1 (191) 456-7890",
//     "address": "Venice, Italy",
//     "progress": 65,
//     "verified": true,
//     "registrationDate": "2019-04-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Venice",
//     "language": "Italian",
//     "tokens": 50
// },
// {
//     "id": 13,
//     "name": "Claire Dubois",
//     "email": "claire.dubois@mail.com",
//     "rating": 4.3,
//     "age": 31,
//     "gender": "female",
//     "phone": "+1 (201) 456-7890",
//     "address": "Marseille, France",
//     "progress": 75,
//     "verified": true,
//     "registrationDate": "2021-05-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Marseille",
//     "language": "French",
//     "tokens": 65
// },
// {
//     "id": 14,
//     "name": "Miguel Torres",
//     "email": "miguel.torres@mail.com",
//     "rating": 3.7,
//     "age": 38,
//     "gender": "male",
//     "phone": "+1 (211) 456-7890",
//     "address": "Valencia, Spain",
//     "progress": 55,
//     "verified": true,
//     "registrationDate": "2022-06-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Valencia",
//     "language": "Spanish",
//     "tokens": 35
// },
// {
//     "id": 15,
//     "name": "Elena Popescu",
//     "email": "elena.popescu@mail.com",
//     "rating": 4.0,
//     "age": 29,
//     "gender": "female",
//     "phone": "+1 (221) 456-7890",
//     "address": "Timisoara, Romania",
//     "progress": 80,
//     "verified": true,
//     "registrationDate": "2020-07-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Romania",
//     "countryCode": "ro",
//     "city": "Timisoara",
//     "language": "Romanian",
//     "tokens": 60
// },
// {
//     "id": 16,
//     "name": "Thomas Müller",
//     "email": "thomas.muller@mail.com",
//     "rating": 4.5,
//     "age": 34,
//     "gender": "male",
//     "phone": "+1 (231) 456-7890",
//     "address": "Munich, Germany",
//     "progress": 90,
//     "verified": true,
//     "registrationDate": "2019-08-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Munich",
//     "language": "German",
//     "tokens": 80
// },
// {
//     "id": 17,
//     "name": "Francesca Romano",
//     "email": "francesca.romano@mail.com",
//     "rating": 3.6,
//     "age": 26,
//     "gender": "female",
//     "phone": "+1 (241) 456-7890",
//     "address": "Florence, Italy",
//     "progress": 70,
//     "verified": true,
//     "registrationDate": "2021-09-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Florence",
//     "language": "Italian",
//     "tokens": 45
// },
// {
//     "id": 18,
//     "name": "Pierre Lambert",
//     "email": "pierre.lambert@mail.com",
//     "rating": 4.2,
//     "age": 33,
//     "gender": "male",
//     "phone": "+1 (251) 456-7890",
//     "address": "Nice, France",
//     "progress": 85,
//     "verified": true,
//     "registrationDate": "2020-10-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Nice",
//     "language": "French",
//     "tokens": 75
// },
// {
//     "id": 19,
//     "name": "Sofia Lopez",
//     "email": "sofia.lopez@mail.com",
//     "rating": 3.8,
//     "age": 30,
//     "gender": "female",
//     "phone": "+1 (261) 456-7890",
//     "address": "Seville, Spain",
//     "progress": 60,
//     "verified": true,
//     "registrationDate": "2022-11-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Seville",
//     "language": "Spanish",
//     "tokens": 40
// },
// {
//     "id": 20,
//     "name": "Andrei Ionescu",
//     "email": "andrei.ionescu@mail.com",
//     "rating": 4.4,
//     "age": 36,
//     "gender": "male",
//     "phone": "+1 (271) 456-7890",
//     "address": "Iasi, Romania",
//     "progress": 95,
//     "verified": true,
//     "registrationDate": "2021-12-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Romania",
//     "countryCode": "ro",
//     "city": "Iasi",
//     "language": "Romanian",
//     "tokens": 90
// },
// {
//     "id": 21,
//     "name": "Laura Müller",
//     "email": "laura.muller@mail.com",
//     "rating": 4.1,
//     "age": 27,
//     "gender": "female",
//     "phone": "+1 (181) 456-7890",
//     "address": "Hamburg, Germany",
//     "progress": 85,
//     "verified": true,
//     "registrationDate": "2020-03-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Hamburg",
//     "language": "German",
//     "tokens": 70
// },
// {
//     "id": 22,
//     "name": "Giuseppe Verdi",
//     "email": "giuseppe.verdi@mail.com",
//     "rating": 3.9,
//     "age": 45,
//     "gender": "male",
//     "phone": "+1 (191) 456-7890",
//     "address": "Venice, Italy",
//     "progress": 65,
//     "verified": true,
//     "registrationDate": "2019-04-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Venice",
//     "language": "Italian",
//     "tokens": 50
// },
// {
//     "id": 23,
//     "name": "Claire Dubois",
//     "email": "claire.dubois@mail.com",
//     "rating": 4.3,
//     "age": 31,
//     "gender": "female",
//     "phone": "+1 (201) 456-7890",
//     "address": "Marseille, France",
//     "progress": 75,
//     "verified": true,
//     "registrationDate": "2021-05-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Marseille",
//     "language": "French",
//     "tokens": 65
// },
// {
//     "id": 24,
//     "name": "Miguel Torres",
//     "email": "miguel.torres@mail.com",
//     "rating": 3.7,
//     "age": 38,
//     "gender": "male",
//     "phone": "+1 (211) 456-7890",
//     "address": "Valencia, Spain",
//     "progress": 55,
//     "verified": true,
//     "registrationDate": "2022-06-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Valencia",
//     "language": "Spanish",
//     "tokens": 35
// },
// {
//     "id": 25,
//     "name": "Elena Popescu",
//     "email": "elena.popescu@mail.com",
//     "rating": 4.0,
//     "age": 29,
//     "gender": "female",
//     "phone": "+1 (221) 456-7890",
//     "address": "Timisoara, Romania",
//     "progress": 80,
//     "verified": true,
//     "registrationDate": "2020-07-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Romania",
//     "countryCode": "ro",
//     "city": "Timisoara",
//     "language": "Romanian",
//     "tokens": 60
// },
// {
//     "id": 26,
//     "name": "Thomas Müller",
//     "email": "thomas.muller@mail.com",
//     "rating": 4.5,
//     "age": 34,
//     "gender": "male",
//     "phone": "+1 (231) 456-7890",
//     "address": "Munich, Germany",
//     "progress": 90,
//     "verified": true,
//     "registrationDate": "2019-08-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Munich",
//     "language": "German",
//     "tokens": 80
// },
// {
//     "id": 27,
//     "name": "Francesca Romano",
//     "email": "francesca.romano@mail.com",
//     "rating": 3.6,
//     "age": 26,
//     "gender": "female",
//     "phone": "+1 (241) 456-7890",
//     "address": "Florence, Italy",
//     "progress": 70,
//     "verified": true,
//     "registrationDate": "2021-09-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Florence",
//     "language": "Italian",
//     "tokens": 45
// },
// {
//     "id": 28,
//     "name": "Pierre Lambert",
//     "email": "pierre.lambert@mail.com",
//     "rating": 4.2,
//     "age": 33,
//     "gender": "male",
//     "phone": "+1 (251) 456-7890",
//     "address": "Nice, France",
//     "progress": 85,
//     "verified": true,
//     "registrationDate": "2020-10-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Nice",
//     "language": "French",
//     "tokens": 75
// },
// {
//     "id": 29,
//     "name": "Sofia Lopez",
//     "email": "sofia.lopez@mail.com",
//     "rating": 3.8,
//     "age": 30,
//     "gender": "female",
//     "phone": "+1 (261) 456-7890",
//     "address": "Seville, Spain",
//     "progress": 60,
//     "verified": true,
//     "registrationDate": "2022-11-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Seville",
//     "language": "Spanish",
//     "tokens": 40
// },
// {
//     "id": 30,
//     "name": "Andrei Ionescu",
//     "email": "andrei.ionescu@mail.com",
//     "rating": 4.4,
//     "age": 36,
//     "gender": "male",
//     "phone": "+1 (271) 456-7890",
//     "address": "Iasi, Romania",
//     "progress": 95,
//     "verified": true,
//     "registrationDate": "2021-12-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Romania",
//     "countryCode": "ro",
//     "city": "Iasi",
//     "language": "Romanian",
//     "tokens": 90
// },
// {
//     "id": 31,
//     "name": "Laura Müller",
//     "email": "laura.muller@mail.com",
//     "rating": 4.1,
//     "age": 27,
//     "gender": "female",
//     "phone": "+1 (181) 456-7890",
//     "address": "Hamburg, Germany",
//     "progress": 85,
//     "verified": true,
//     "registrationDate": "2020-03-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Hamburg",
//     "language": "German",
//     "tokens": 70
// },
// {
//     "id": 32,
//     "name": "Giuseppe Verdi",
//     "email": "giuseppe.verdi@mail.com",
//     "rating": 3.9,
//     "age": 45,
//     "gender": "male",
//     "phone": "+1 (191) 456-7890",
//     "address": "Venice, Italy",
//     "progress": 65,
//     "verified": true,
//     "registrationDate": "2019-04-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Venice",
//     "language": "Italian",
//     "tokens": 50
// },
// {
//     "id": 33,
//     "name": "Claire Dubois",
//     "email": "claire.dubois@mail.com",
//     "rating": 4.3,
//     "age": 31,
//     "gender": "female",
//     "phone": "+1 (201) 456-7890",
//     "address": "Marseille, France",
//     "progress": 75,
//     "verified": true,
//     "registrationDate": "2021-05-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Marseille",
//     "language": "French",
//     "tokens": 65
// },
// {
//     "id": 34,
//     "name": "Miguel Torres",
//     "email": "miguel.torres@mail.com",
//     "rating": 3.7,
//     "age": 38,
//     "gender": "male",
//     "phone": "+1 (211) 456-7890",
//     "address": "Valencia, Spain",
//     "progress": 55,
//     "verified": true,
//     "registrationDate": "2022-06-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Valencia",
//     "language": "Spanish",
//     "tokens": 35
// },
// {
//     "id": 35,
//     "name": "Elena Popescu",
//     "email": "elena.popescu@mail.com",
//     "rating": 4.0,
//     "age": 29,
//     "gender": "female",
//     "phone": "+1 (221) 456-7890",
//     "address": "Timisoara, Romania",
//     "progress": 80,
//     "verified": true,
//     "registrationDate": "2020-07-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Romania",
//     "countryCode": "ro",
//     "city": "Timisoara",
//     "language": "Romanian",
//     "tokens": 60
// },
// {
//     "id": 36,
//     "name": "Thomas Müller",
//     "email": "thomas.muller@mail.com",
//     "rating": 4.5,
//     "age": 34,
//     "gender": "male",
//     "phone": "+1 (231) 456-7890",
//     "address": "Munich, Germany",
//     "progress": 90,
//     "verified": true,
//     "registrationDate": "2019-08-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Munich",
//     "language": "German",
//     "tokens": 80
// },
// {
//     "id": 37,
//     "name": "Francesca Romano",
//     "email": "francesca.romano@mail.com",
//     "rating": 3.6,
//     "age": 26,
//     "gender": "female",
//     "phone": "+1 (241) 456-7890",
//     "address": "Florence, Italy",
//     "progress": 70,
//     "verified": true,
//     "registrationDate": "2021-09-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Florence",
//     "language": "Italian",
//     "tokens": 45
// },
// {
//     "id": 38,
//     "name": "Pierre Lambert",
//     "email": "pierre.lambert@mail.com",
//     "rating": 4.2,
//     "age": 33,
//     "gender": "male",
//     "phone": "+1 (251) 456-7890",
//     "address": "Nice, France",
//     "progress": 85,
//     "verified": true,
//     "registrationDate": "2020-10-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Nice",
//     "language": "French",
//     "tokens": 75
// },
// {
//     "id": 39,
//     "name": "Sofia Lopez",
//     "email": "sofia.lopez@mail.com",
//     "rating": 3.8,
//     "age": 30,
//     "gender": "female",
//     "phone": "+1 (261) 456-7890",
//     "address": "Seville, Spain",
//     "progress": 60,
//     "verified": true,
//     "registrationDate": "2022-11-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Seville",
//     "language": "Spanish",
//     "tokens": 40
// },
// {
//     "id": 40,
//     "name": "Andrei Ionescu",
//     "email": "andrei.ionescu@mail.com",
//     "rating": 4.4,
//     "age": 36,
//     "gender": "male",
//     "phone": "+1 (271) 456-7890",
//     "address": "Iasi, Romania",
//     "progress": 95,
//     "verified": true,
//     "registrationDate": "2021-12-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Romania",
//     "countryCode": "ro",
//     "city": "Iasi",
//     "language": "Romanian",
//     "tokens": 90
// }, 
// {
//     "id": 41,
//     "name": "Laura Müller",
//     "email": "laura.muller@mail.com",
//     "rating": 4.1,
//     "age": 27,
//     "gender": "female",
//     "phone": "+1 (181) 456-7890",
//     "address": "Hamburg, Germany",
//     "progress": 85,
//     "verified": true,
//     "registrationDate": "2020-03-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Hamburg",
//     "language": "German",
//     "tokens": 70
// },
// {
//     "id": 42,
//     "name": "Giuseppe Verdi",
//     "email": "giuseppe.verdi@mail.com",
//     "rating": 3.9,
//     "age": 45,
//     "gender": "male",
//     "phone": "+1 (191) 456-7890",
//     "address": "Venice, Italy",
//     "progress": 65,
//     "verified": true,
//     "registrationDate": "2019-04-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Venice",
//     "language": "Italian",
//     "tokens": 50
// },
// {
//     "id": 43,
//     "name": "Claire Dubois",
//     "email": "claire.dubois@mail.com",
//     "rating": 4.3,
//     "age": 31,
//     "gender": "female",
//     "phone": "+1 (201) 456-7890",
//     "address": "Marseille, France",
//     "progress": 75,
//     "verified": true,
//     "registrationDate": "2021-05-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Marseille",
//     "language": "French",
//     "tokens": 65
// },
// {
//     "id": 44,
//     "name": "Miguel Torres",
//     "email": "miguel.torres@mail.com",
//     "rating": 3.7,
//     "age": 38,
//     "gender": "male",
//     "phone": "+1 (211) 456-7890",
//     "address": "Valencia, Spain",
//     "progress": 55,
//     "verified": true,
//     "registrationDate": "2022-06-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Valencia",
//     "language": "Spanish",
//     "tokens": 35
// },
// {
//     "id": 45,
//     "name": "Elena Popescu",
//     "email": "elena.popescu@mail.com",
//     "rating": 4.0,
//     "age": 29,
//     "gender": "female",
//     "phone": "+1 (221) 456-7890",
//     "address": "Timisoara, Romania",
//     "progress": 80,
//     "verified": true,
//     "registrationDate": "2020-07-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Romania",
//     "countryCode": "ro",
//     "city": "Timisoara",
//     "language": "Romanian",
//     "tokens": 60
// },
// {
//     "id": 46,
//     "name": "Thomas Müller",
//     "email": "thomas.muller@mail.com",
//     "rating": 4.5,
//     "age": 34,
//     "gender": "male",
//     "phone": "+1 (231) 456-7890",
//     "address": "Munich, Germany",
//     "progress": 90,
//     "verified": true,
//     "registrationDate": "2019-08-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Munich",
//     "language": "German",
//     "tokens": 80
// },
// {
//     "id": 47,
//     "name": "Francesca Romano",
//     "email": "francesca.romano@mail.com",
//     "rating": 3.6,
//     "age": 26,
//     "gender": "female",
//     "phone": "+1 (241) 456-7890",
//     "address": "Florence, Italy",
//     "progress": 70,
//     "verified": true,
//     "registrationDate": "2021-09-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Florence",
//     "language": "Italian",
//     "tokens": 45
// },
// {
//     "id": 48,
//     "name": "Pierre Lambert",
//     "email": "pierre.lambert@mail.com",
//     "rating": 4.2,
//     "age": 33,
//     "gender": "male",
//     "phone": "+1 (251) 456-7890",
//     "address": "Nice, France",
//     "progress": 85,
//     "verified": true,
//     "registrationDate": "2020-10-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Nice",
//     "language": "French",
//     "tokens": 75
// },
// {
//     "id": 49,
//     "name": "Sofia Lopez",
//     "email": "sofia.lopez@mail.com",
//     "rating": 3.8,
//     "age": 30,
//     "gender": "female",
//     "phone": "+1 (261) 456-7890",
//     "address": "Seville, Spain",
//     "progress": 60,
//     "verified": true,
//     "registrationDate": "2022-11-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Seville",
//     "language": "Spanish",
//     "tokens": 40
// },
// {
//     "id": 50,
//     "name": "Andrei Ionescu",
//     "email": "andrei.ionescu@mail.com",
//     "rating": 4.4,
//     "age": 36,
//     "gender": "male",
//     "phone": "+1 (271) 456-7890",
//     "address": "Iasi, Romania",
//     "progress": 95,
//     "verified": true,
//     "registrationDate": "2021-12-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Romania",
//     "countryCode": "ro",
//     "city": "Iasi",
//     "language": "Romanian",
//     "tokens": 90
// },
// {
//     "id": 51,
//     "name": "Laura Müller",
//     "email": "laura.muller@mail.com",
//     "rating": 4.1,
//     "age": 27,
//     "gender": "female",
//     "phone": "+1 (181) 456-7890",
//     "address": "Hamburg, Germany",
//     "progress": 85,
//     "verified": true,
//     "registrationDate": "2020-03-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Hamburg",
//     "language": "German",
//     "tokens": 70
// },
// {
//     "id": 52,
//     "name": "Giuseppe Verdi",
//     "email": "giuseppe.verdi@mail.com",
//     "rating": 3.9,
//     "age": 45,
//     "gender": "male",
//     "phone": "+1 (191) 456-7890",
//     "address": "Venice, Italy",
//     "progress": 65,
//     "verified": true,
//     "registrationDate": "2019-04-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Venice",
//     "language": "Italian",
//     "tokens": 50
// },
// {
//     "id": 53,
//     "name": "Claire Dubois",
//     "email": "claire.dubois@mail.com",
//     "rating": 4.3,
//     "age": 31,
//     "gender": "female",
//     "phone": "+1 (201) 456-7890",
//     "address": "Marseille, France",
//     "progress": 75,
//     "verified": true,
//     "registrationDate": "2021-05-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Marseille",
//     "language": "French",
//     "tokens": 65
// },
// {
//     "id": 54,
//     "name": "Miguel Torres",
//     "email": "miguel.torres@mail.com",
//     "rating": 3.7,
//     "age": 38,
//     "gender": "male",
//     "phone": "+1 (211) 456-7890",
//     "address": "Valencia, Spain",
//     "progress": 55,
//     "verified": true,
//     "registrationDate": "2022-06-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Valencia",
//     "language": "Spanish",
//     "tokens": 35
// },
// {
//     "id": 55,
//     "name": "Elena Popescu",
//     "email": "elena.popescu@mail.com",
//     "rating": 4.0,
//     "age": 29,
//     "gender": "female",
//     "phone": "+1 (221) 456-7890",
//     "address": "Timisoara, Romania",
//     "progress": 80,
//     "verified": true,
//     "registrationDate": "2020-07-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Romania",
//     "countryCode": "ro",
//     "city": "Timisoara",
//     "language": "Romanian",
//     "tokens": 60
// },
// {
//     "id": 56,
//     "name": "Thomas Müller",
//     "email": "thomas.muller@mail.com",
//     "rating": 4.5,
//     "age": 34,
//     "gender": "male",
//     "phone": "+1 (231) 456-7890",
//     "address": "Munich, Germany",
//     "progress": 90,
//     "verified": true,
//     "registrationDate": "2019-08-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Munich",
//     "language": "German",
//     "tokens": 80
// },
// {
//     "id": 57,
//     "name": "Francesca Romano",
//     "email": "francesca.romano@mail.com",
//     "rating": 3.6,
//     "age": 26,
//     "gender": "female",
//     "phone": "+1 (241) 456-7890",
//     "address": "Florence, Italy",
//     "progress": 70,
//     "verified": true,
//     "registrationDate": "2021-09-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Florence",
//     "language": "Italian",
//     "tokens": 45
// },
// {
//     "id": 58,
//     "name": "Pierre Lambert",
//     "email": "pierre.lambert@mail.com",
//     "rating": 4.2,
//     "age": 33,
//     "gender": "male",
//     "phone": "+1 (251) 456-7890",
//     "address": "Nice, France",
//     "progress": 85,
//     "verified": true,
//     "registrationDate": "2020-10-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Nice",
//     "language": "French",
//     "tokens": 75
// },
// {
//     "id": 59,
//     "name": "Sofia Lopez",
//     "email": "sofia.lopez@mail.com",
//     "rating": 3.8,
//     "age": 30,
//     "gender": "female",
//     "phone": "+1 (261) 456-7890",
//     "address": "Seville, Spain",
//     "progress": 60,
//     "verified": true,
//     "registrationDate": "2022-11-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Seville",
//     "language": "Spanish",
//     "tokens": 40
// },
// {
//     "id": 60,
//     "name": "Andrei Ionescu",
//     "email": "andrei.ionescu@mail.com",
//     "rating": 4.4,
//     "age": 36,
//     "gender": "male",
//     "phone": "+1 (271) 456-7890",
//     "address": "Iasi, Romania",
//     "progress": 95,
//     "verified": true,
//     "registrationDate": "2021-12-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Romania",
//     "countryCode": "ro",
//     "city": "Iasi",
//     "language": "Romanian",
//     "tokens": 90
// }
// ,
// {
//     "id": 61,
//     "name": "Laura Müller",
//     "email": "laura.muller@mail.com",
//     "rating": 4.1,
//     "age": 27,
//     "gender": "female",
//     "phone": "+1 (181) 456-7890",
//     "address": "Hamburg, Germany",
//     "progress": 85,
//     "verified": true,
//     "registrationDate": "2020-03-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Hamburg",
//     "language": "German",
//     "tokens": 70
// },
// {
//     "id": 62,
//     "name": "Giuseppe Verdi",
//     "email": "giuseppe.verdi@mail.com",
//     "rating": 3.9,
//     "age": 45,
//     "gender": "male",
//     "phone": "+1 (191) 456-7890",
//     "address": "Venice, Italy",
//     "progress": 65,
//     "verified": true,
//     "registrationDate": "2019-04-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Venice",
//     "language": "Italian",
//     "tokens": 50
// },
// {
//     "id": 63,
//     "name": "Claire Dubois",
//     "email": "claire.dubois@mail.com",
//     "rating": 4.3,
//     "age": 31,
//     "gender": "female",
//     "phone": "+1 (201) 456-7890",
//     "address": "Marseille, France",
//     "progress": 75,
//     "verified": true,
//     "registrationDate": "2021-05-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Marseille",
//     "language": "French",
//     "tokens": 65
// },
// {
//     "id": 64,
//     "name": "Miguel Torres",
//     "email": "miguel.torres@mail.com",
//     "rating": 3.7,
//     "age": 38,
//     "gender": "male",
//     "phone": "+1 (211) 456-7890",
//     "address": "Valencia, Spain",
//     "progress": 55,
//     "verified": true,
//     "registrationDate": "2022-06-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Valencia",
//     "language": "Spanish",
//     "tokens": 35
// },
// {
//     "id": 65,
//     "name": "Elena Popescu",
//     "email": "elena.popescu@mail.com",
//     "rating": 4.0,
//     "age": 29,
//     "gender": "female",
//     "phone": "+1 (221) 456-7890",
//     "address": "Timisoara, Romania",
//     "progress": 80,
//     "verified": true,
//     "registrationDate": "2020-07-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Romania",
//     "countryCode": "ro",
//     "city": "Timisoara",
//     "language": "Romanian",
//     "tokens": 60
// },
// {
//     "id": 66,
//     "name": "Thomas Müller",
//     "email": "thomas.muller@mail.com",
//     "rating": 4.5,
//     "age": 34,
//     "gender": "male",
//     "phone": "+1 (231) 456-7890",
//     "address": "Munich, Germany",
//     "progress": 90,
//     "verified": true,
//     "registrationDate": "2019-08-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Germany",
//     "countryCode": "de",
//     "city": "Munich",
//     "language": "German",
//     "tokens": 80
// },
// {
//     "id": 67,
//     "name": "Francesca Romano",
//     "email": "francesca.romano@mail.com",
//     "rating": 3.6,
//     "age": 26,
//     "gender": "female",
//     "phone": "+1 (241) 456-7890",
//     "address": "Florence, Italy",
//     "progress": 70,
//     "verified": true,
//     "registrationDate": "2021-09-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Italy",
//     "countryCode": "it",
//     "city": "Florence",
//     "language": "Italian",
//     "tokens": 45
// },
// {
//     "id": 68,
//     "name": "Pierre Lambert",
//     "email": "pierre.lambert@mail.com",
//     "rating": 4.2,
//     "age": 33,
//     "gender": "male",
//     "phone": "+1 (251) 456-7890",
//     "address": "Nice, France",
//     "progress": 85,
//     "verified": true,
//     "registrationDate": "2020-10-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "France",
//     "countryCode": "fr",
//     "city": "Nice",
//     "language": "French",
//     "tokens": 75
// },
// {
//     "id": 69,
//     "name": "Sofia Lopez",
//     "email": "sofia.lopez@mail.com",
//     "rating": 3.8,
//     "age": 30,
//     "gender": "female",
//     "phone": "+1 (261) 456-7890",
//     "address": "Seville, Spain",
//     "progress": 60,
//     "verified": true,
//     "registrationDate": "2022-11-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Spain",
//     "countryCode": "es",
//     "city": "Seville",
//     "language": "Spanish",
//     "tokens": 40
// },
// {
//     "id": 70,
//     "name": "Andrei Ionescu",
//     "email": "andrei.ionescu@mail.com",
//     "rating": 4.4,
//     "age": 36,
//     "gender": "male",
//     "phone": "+1 (271) 456-7890",
//     "address": "Iasi, Romania",
//     "progress": 95,
//     "verified": true,
//     "registrationDate": "2021-12-01T00:00:00.000Z",
//     "status": "Active",
//     "role": "User",
//     "country": "Romania",
//     "countryCode": "ro",
//     "city": "Iasi",
//     "language": "Romanian",
//     "tokens": 90
// }






];


export const KeepItSimpleTable = () => {
    const [filter, setFilter] = useState<Filter>({});
    const [order, setOrder] = useState<{ order: Order, sortBy: string }>({ order: 'asc', sortBy: 'name' });
    const contentManagerSelection = useSelection<number>();
    const [loading, setLoading] = useState<boolean>(false);
    const [empty, setEmpty] = useState<boolean>(false);
    const [showFilter, setShowFilter] = useState<boolean>(true);
    const [showFooter, setShowFooter] = useState<boolean>(true);
    const [showRowSelection, setShowRowSelection] = useState<boolean>(true);
    const [showRowExpansion, setShowRowExpansion] = useState<boolean>(true);
    const [showRowActions, setShowRowActions] = useState<boolean>(true); 

    const headCells: ColumnDef[] = useMemo(() =>[{
        id: 'id',
        header: 'ID',
        width: 80,
        cell: (row: any) => row.id,
    }, {
        id: 'name',
        header: 'Name',
        width: 200,
        hasSort: true,
        cell: (row: any) => (<Stack direction="row" alignItems="center" gap={1}><Avatar  {...stringAvatar(row.name)} />{row.name}</Stack>),
		pin: createResponsivePin('left', 'sm', 'up'),
        highlight: true,
    }, {
        id: 'email',
        header: 'E-mail',
        width: 200,
        hasSort: true,
        cell: (row: any) => row.email,
    }, {
        id: 'country',
        header: 'Country',
        width: 150,
        hasSort: true,
		pin: createResponsivePin('left', 'md', 'up'),
        cell: (row: any) => <Stack direction="row" alignItems="center" gap={1}><CountryIcon country={row.countryCode}
            sx={{
                fontSize: 24,
                color: 'primary.main'
            }}
        />
            {row.country}
        </Stack>,
    }, {
        id: 'city',
        header: 'City',
        width: 150,
        hasSort: true,
        cell: (row: any) => row.city,
    }, {
        id: 'age',
        header: 'Age',
        width: 80,
        hasSort: true,
        cell: (row: any) => row.age,
    }, {
        id: 'gender',
        header: 'Gender',
        width: 100,
        hasSort: true,
        cell: (row: any) => row.gender,
    }, {
        id: 'address',
        header: 'Address',
        width: 200,
        hasSort: true,
        cell: (row: any) => row.address,
    }, {
        id: 'phone',
        header: 'Phone',
        width: 150,
        cell: (row: any) => row.phone,
    }, {
        id: 'status',
        header: 'Status',
        width: 120,
        hasSort: true,
        cell: (row: any) => {
            if (row.status === 'Active') {
                return (<Chip label="Active" color="primary" size="small" />);
            } else {
                return (<Chip label="Inactive" color="secondary" size="small" />);
            }
        }
    }, {
        id: 'tokens',
        header: 'Tokens',
        width: 100,
        hasSort: true,
		pin: createResponsivePin(true, 'lg', 'up'),
        cell: (row: any) => row.tokens,
    }, {
        id: 'language',
        header: 'Language',
        width: 150,
        hasSort: true,
        cell: (row: any) => row.language,
    }, {
        id: 'progress',
        header: 'Progress',
        width: 100,
        cell: (row: any) => <LinearProgress color="success" value={row.progress} variant="determinate" />,
    }, {
        id: 'Verified',
        header: 'verified',
        width: 100,
        hasSort: true,
        cell: (row: any) => row.verified ? 'Yes' : 'No',
    }, {
        id: 'registrationDate',
        header: 'Registered On',
        width: 210,
        hasSort: true,
        cell: (row: any) => <>{dayjs(row.registrationDate).format('MMM DD, YYYY, hh:mm:ss A')}</>,
        //visible: useResponsiveHeadCellVisible({ breakpoint: 'md', direction: 'up' }),
    }, {
        id: 'role',
        header: 'Role',
        width: 120,
        hasSort: true,
        cell: (row: any) => row.role,
    }, {
        id: 'rating',
        header: 'Rating',
        width: 180,
        cell: (row: any) => <Rating name="half-rating" defaultValue={row.rating} precision={0.5} readOnly />,
    }], []);

    let items = empty ? [] : data;

    const isColumnHighlighted = useCallback((headCellId: string) => {
        return headCellId === 'role';
    }, []);

    // Row Actions
    const todoActions: Action<any>[] = useMemo(() => ([
        {
            id: 'edit',
            render: (field: any) => (<MenuItem id='edit-menu-item' key={`edit-${field}`} > <ListItemIcon><EditIcon /></ListItemIcon> Edit </MenuItem>)
        },
        {
            id: 'remove',
            render: (field: any) => (<MenuItem id='remove-menu-item' key={`remove-${field}`} > <ListItemIcon><DeleteIcon /></ListItemIcon> Remove </MenuItem>)
        },
    ]), []);


	const rowDetailStore = useMemo(() => createRowDetailStore<any>(), []);

    const gridPlugins = useGridPlugins(
        // process the 'render' function
        CustomBodyCellContentRenderPlugin,


        usePluginWithParams(FilterRowPlugin, {
            visible: showFilter,
            //filter: filter,
			store: useMemo(() => createFilterRowStore<any>(), []),
            filterChanged: setFilter,
            key: 'filter_row',
            filterColumns: useMemo<any>(() => ({
                'name': 'string',
                'city': {
                    type: 'string',
                    ...DefaultStringFilterOptions,
                },
                'email': {
                    type: 'string',
                    operators: [{ value: 'contains', label: 'Contains', iconText: '@' }, { value: 'starts-with', label: 'Starts With', iconText: '@[' }],
                    defaultOperator: 'contains'
                },
                'country': {
                    type: 'select',
                    selectOptions: [
                        { value: 'Austria', label: 'Austria' },
                        { value: 'Brazil', label: 'Brazil' },
                        { value: 'Cyprus', label: 'Cyprus' },
                        { value: 'France', label: 'France' },
                        { value: 'Italy', label: 'Italy' },
                        { value: 'Japan', label: 'Japan' },
                        { value: 'Romania', label: 'Romania' },
                        { value: 'South Africa', label: 'South Africa' },
                        { value: 'USA', label: 'USA' },
                    ],
                },
                'registrationDate': 'date',
                'tokens': {
                    type: 'number',
                    ...DefaultNumberDateFilterOptions,
                },
            }), [])
        }),

        // add summary row. You can add as many summary rows as you want
        usePluginWithParams(SummaryRowPlugin, {
            visible: showFooter,
            key: 'symmary_row', // needed only if you want to use more than one summary row
            summaryColumns: useMemo(() => ({
                'name': (column: ColumnDef<any>) => <Typography fontWeight={700}>Total</Typography>,
                'tokens': (column: ColumnDef<any>) => <Typography fontWeight={700}>338</Typography>,
            }), [])
        }),

        // add padding to the table cells
        usePluginWithParams(PaddingPluggin, {}),

        // add sorting functionality
        usePluginWithParams(ColumnSortPlugin, {
            order: order.order,
            orderBy: order.sortBy,
            onSort: useCallback((sortBy: string, sortOrder: Order) => { setOrder({ order: sortOrder, sortBy: sortBy }) }, [setOrder])
        }),

        // add row selection functionality (checlbox column)
        usePluginWithParams(RowSelectionPlugin, {
            visible: showRowSelection,
            onGetRowId: useCallback((row: any) => row.id, []),
            onSelectOne: contentManagerSelection.handleSelectOne,
            onDeselectOne: contentManagerSelection.handleDeselectOne,
            //selectedIds: contentManagerSelection.selected

			rowSelectionStore: useMemo(() => createRowSelectionStore<any>(), [])
        }),

        usePluginWithParams(RowDetailPlugin, {
            showExpanderButton: showRowExpansion,
            onGetRowId: useCallback((row: any) => row.id, []),
            rowDetailStore: rowDetailStore,
            getExpansionNode: useCallback((row: any, params: any) => (<AbsoluteHeightContainer sx={{ p: 5 }}>Hello {row.name}</AbsoluteHeightContainer>), [])
        }),

        // Fill the space between the last column and the actions. Needed when only a few columns are fixed-width to push the action column to the right.
        ColumnsFillRowSpacePlugin,

        // add actions column
        usePluginWithParams(RowActionsPlugin, {
            actions: todoActions,
            visible: showRowActions
        }),

        // add column highlighting functionality
        usePluginWithParams(HighlightColumnPlugin, {
            isColumnHighlighted: isColumnHighlighted
        }),

        // Required for pinned columns when the table is scrolled. Marking a column as pinned alone isn’t enough; this plugin ensures the column stays in place.
        usePluginWithParams(PinnedColumnsPlugin, { }),

        // add skeleton loading state visualization
        usePluginWithParams(SkeletonLoadingPlugin, {
            isLoading: loading
        }),

        // add empty table state visualization
        usePluginWithParams(EmptyDataPlugin, {
            content: "Wow, such empty!"
        }),
    );

    return (
        <>
            <Stack alignItems="center" direction="row" justifyContent="flex-end" flexWrap="wrap" sx={{marginBottom: 5}} >
                <FormControlLabel control={<Checkbox checked={showFilter} onChange={(event) => setShowFilter(event.target.checked)} />} label="Show Filters" />
                <FormControlLabel control={<Checkbox checked={showRowExpansion} onChange={(event) => setShowRowExpansion(event.target.checked)} />} label="Show Row Detail" />
                <FormControlLabel control={<Checkbox checked={showRowSelection} onChange={(event) => setShowRowSelection(event.target.checked)} />} label="Show Row Selection" />
                <FormControlLabel control={<Checkbox checked={showFooter} onChange={(event) => setShowFooter(event.target.checked)} />} label="Show Footer" />
                <FormControlLabel control={<Checkbox checked={empty} onChange={(event) => setEmpty(event.target.checked)} />} label="Simulate Empty Table" />
                <FormControlLabel control={<Checkbox checked={loading} onChange={(event) => setLoading(event.target.checked)} />} label="Simulate Loading" />
                <FormControlLabel control={<Checkbox checked={showRowActions} onChange={(event) => setShowRowActions(event.target.checked)} />} label="Row Actions" />  
            </Stack>

            <MosaicDataTable
                caption="Keep it simple table" // not visible. used for accessibility
                plugins={gridPlugins}
                headCells={headCells}
                items={items}
            />

			<Button onClick={() => {
				console.log(rowDetailStore.getKeys());
				rowDetailStore.clear();
			}}>Close All</Button>
        </>
    )
}